# Generated by Django 2.0.4 on 2018-04-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('pic', models.ImageField(upload_to='posts/')),
                ('body', models.TextField()),
                ('pub_date', models.DateField(auto_now=True)),
                ('mod_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
