# Generated by Django 2.0.4 on 2018-04-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mod_date',
            field=models.DateField(),
        ),
    ]
